# Generated by Django 4.2.3 on 2023-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macgrievance',
            name='department_name',
            field=models.CharField(default='mca', max_length=250),
            preserve_default=False,
        ),
    ]
