# Generated by Django 4.2.3 on 2023-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macgrievance',
            name='feedback',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
