# Generated by Django 4.2.3 on 2023-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0002_macgrievance_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macgrievance',
            name='department_name',
        ),
        migrations.AddField(
            model_name='macgrievance',
            name='grievance_type',
            field=models.CharField(default='blsnk', max_length=200),
            preserve_default=False,
        ),
    ]
