# Generated by Django 4.2.3 on 2023-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0002_macgrievance_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_sub', models.CharField(max_length=100)),
                ('feed_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='macgrievance',
            name='feedback',
        ),
    ]
