# Generated by Django 4.2.3 on 2023-07-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0003_remove_macgrievance_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macgrievance',
            name='grievance_description',
        ),
    ]
