# Generated by Django 4.2.3 on 2023-08-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0004_macgrievance_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macgrievance',
            name='username',
        ),
    ]
