# Generated by Django 4.2.3 on 2023-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0004_remove_macgrievance_grievance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='macgrievance',
            name='grievance_description',
            field=models.TextField(default='mca'),
            preserve_default=False,
        ),
    ]
