# Generated by Django 4.2.3 on 2023-08-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0005_remove_macgrievance_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='macgrievance',
            name='name',
            field=models.CharField(default='o', max_length=100),
            preserve_default=False,
        ),
    ]
