# Generated by Django 4.2.3 on 2023-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0005_macgrievance_grievance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='macgrievance',
            name='department',
            field=models.CharField(default='dept', max_length=200),
            preserve_default=False,
        ),
    ]
