# Generated by Django 4.2.3 on 2023-08-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0006_macgrievance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macgrievance',
            name='name',
        ),
    ]
