# Generated by Django 4.2.3 on 2023-07-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0006_macgrievance_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macgrievance',
            name='department',
        ),
    ]
