# Generated by Django 4.2.3 on 2023-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0009_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='macgrievance',
            name='course',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA'), ('MSC', 'MSC')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='macgrievance',
            name='grievance_type',
            field=models.CharField(choices=[('ClassRoom', 'ClassRoom'), ('Teacher', 'Teacher'), ('Management', 'Management'), ('College', 'College'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
