# Generated by Django 4.2.3 on 2023-08-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0011_remove_macgrievance_course_macgrievance_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='department',
            field=models.CharField(default='MCA', max_length=200),
            preserve_default=False,
        ),
    ]
