# Generated by Django 4.2.3 on 2023-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_app', '0019_alter_macgrievance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macgrievance',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('InProgress', 'InProgress'), ('Pending', 'Pending'), ('Unsolved', 'Unsolved')], default='Pending', max_length=100),
        ),
    ]
